blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability (Private)
    url: https://github.com/Yigtwxx/bsglab/security/advisories/new
    about: Please report potential vulnerabilities privately.
